Ft borrar monitorias
Campus-Connect-PUJ/Campus-Connect-Back pull request #39
Opened 2021-04-30 19:53 UTC by kamilo2299

Se pueden borrar monitorias

2021-05-03 20:40 UTC, dhasane requested changes

2021-05-03 20:40 UTC, dhasane commented on src/main/java/CampusConnect/CCBack/Model/Horario.java
> +	public String lugar;
Ya hay una clase que se encarga del manejo del lugar, no se si sea mejor usarla en vez de un string

2021-05-03 20:40 UTC, dhasane commented on src/main/java/CampusConnect/CCBack/Security/SecurityConfig.java
> +                    //"/**",
:v

2021-05-03 20:40 UTC, dhasane commented on src/main/java/CampusConnect/CCBack/Security/SecurityConfig.java
> +                    //"/**",
pues sirve

2021-05-03 20:40 UTC, dhasane commented on src/main/java/CampusConnect/CCBack/Service/UsuarioGeneralService.java
> +            repository.save(ug);
Por la forma en la que se esta haciendo el manejo de las excepciones, es mejor usar lo siguiente en vez del repositorio 
GenericService.save(repository, ug);
De ser posible, por favor intente nunca usar el repositorio directamente, o en caso de ser necesario, ponerle la excepcion.

2021-05-03 21:09 UTC, kamilo2299 commented on src/main/java/CampusConnect/CCBack/Model/Horario.java
> +	public String lugar;
Son diferentes lugares. 
En el backend los lugares son para los restaurantes y pues los otros lugares son sitios de la universidad

2021-05-03 21:09 UTC, kamilo2299 commented on src/main/java/CampusConnect/CCBack/Model/Horario.java
> +	public String lugar;
Son diferentes lugares. 
En el backend los lugares son para los restaurantes y pues los otros lugares son sitios de la universidad

2021-05-03 21:33 UTC, dhasane commented on src/main/java/CampusConnect/CCBack/Model/Horario.java
> +	public String lugar;
Me parece recordar que los lugares pueden representar cualquier sitio dentro de la universidad, por lo que serviria para esto

2021-05-03 21:40 UTC, kamilo2299 commented on src/main/java/CampusConnect/CCBack/Model/Horario.java
> +	public String lugar;
Revise y puede mirar que no están creados...
Haría referencia a un lugar que no existe, por lo que no podria buscarlo por id o nombre. Haciendo que de error

2021-05-04 04:03 UTC, dhasane commented on src/main/java/CampusConnect/CCBack/Model/Horario.java
> +	public String lugar;
hmmm, mejor dejarlo de esta forma de momento, entonces, pero creo que lo mejor si seria pasarlo a lo otro

2021-05-04 04:03 UTC, dhasane approved these changes

2021-05-04 04:04 UTC, merged