Ft sugerencias final
Campus-Connect-PUJ/Campus-Connect-Back pull request #45
Opened 2021-05-14 17:51 UTC by Laura-Mora

Mini cambios

2021-05-14 17:58 UTC, dhasane requested changes

2021-05-14 17:58 UTC, dhasane commented on src/main/resources/application.properties
> +spring.jpa.hibernate.ddl-auto=create-drop
esto mejor dejarlo en update

2021-05-16 16:40 UTC, Laura-Mora commented
Ya hice la mini corrección

2021-05-18 00:39 UTC, dhasane approved these changes

2021-05-18 00:39 UTC, merged